// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdphBZ4X7uN6rW_kkRMeMDko6IAS9FTDI',
    appId: '1:330365143644:android:8a05d6d35adfaf9e7a7499',
    messagingSenderId: '330365143644',
    projectId: 'chowqwiklogis',
    storageBucket: 'chowqwiklogis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHwslpz2XFEQcgV8eXHvrsPl522YDtgDw',
    appId: '1:330365143644:ios:544da2efb6071ab77a7499',
    messagingSenderId: '330365143644',
    projectId: 'chowqwiklogis',
    storageBucket: 'chowqwiklogis.appspot.com',
    iosBundleId: 'com.foodies.customer.ios',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFDj5lO3u83BluqCr9flvygaPjs3jqvas',
    appId: '1:330365143644:web:4f2873c56157a4df7a7499',
    messagingSenderId: '330365143644',
    projectId: 'chowqwiklogis',
    authDomain: 'chowqwiklogis.firebaseapp.com',
    storageBucket: 'chowqwiklogis.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHwslpz2XFEQcgV8eXHvrsPl522YDtgDw',
    appId: '1:330365143644:ios:c3fc674ce3b1359d7a7499',
    messagingSenderId: '330365143644',
    projectId: 'chowqwiklogis',
    storageBucket: 'chowqwiklogis.appspot.com',
    iosBundleId: 'chowqwiklogis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFDj5lO3u83BluqCr9flvygaPjs3jqvas',
    appId: '1:330365143644:web:22f1e2de1ab4b2e77a7499',
    messagingSenderId: '330365143644',
    projectId: 'chowqwiklogis',
    authDomain: 'chowqwiklogis.firebaseapp.com',
    storageBucket: 'chowqwiklogis.appspot.com',
  );

}