// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbZYC7Jj97ApoL6tm5ab6iTBLlWnvJBxg',
    appId: '1:81773247098:android:b19ae27d63fbfbb9e499c3',
    messagingSenderId: '81773247098',
    projectId: 'foodiesdriverlogis',
    storageBucket: 'foodiesdriverlogis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe3xyJ-eOH4fsqwEPVkUgw7uMClNH0mb4',
    appId: '1:81773247098:ios:4ba9d855b6756725e499c3',
    messagingSenderId: '81773247098',
    projectId: 'foodiesdriverlogis',
    storageBucket: 'foodiesdriverlogis.appspot.com',
    iosBundleId: 'com.foodies.driver.ios',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJUPYpcxwcwR89-wPRM3sosqWnJENBi7k',
    appId: '1:81773247098:web:58e1a6c86fb82d7ae499c3',
    messagingSenderId: '81773247098',
    projectId: 'foodiesdriverlogis',
    authDomain: 'foodiesdriverlogis.firebaseapp.com',
    storageBucket: 'foodiesdriverlogis.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe3xyJ-eOH4fsqwEPVkUgw7uMClNH0mb4',
    appId: '1:81773247098:ios:920cd53d10dca11fe499c3',
    messagingSenderId: '81773247098',
    projectId: 'foodiesdriverlogis',
    storageBucket: 'foodiesdriverlogis.appspot.com',
    iosBundleId: 'com.foodies.driver.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJUPYpcxwcwR89-wPRM3sosqWnJENBi7k',
    appId: '1:81773247098:web:36502e77c6f76108e499c3',
    messagingSenderId: '81773247098',
    projectId: 'foodiesdriverlogis',
    authDomain: 'foodiesdriverlogis.firebaseapp.com',
    storageBucket: 'foodiesdriverlogis.appspot.com',
  );

}